### PR TITLE
CF conventions

### PR DESCRIPTION
**Pull request by jessecusack**
Unfinished pull request.

The possibly problematic change here is the conversion of time from datetime64 to 'seconds since 1970-01-01', which might not be backward compatible. The advantage of this change is that xarray understands the new format and can automatically decode and convert to datetime64 and it is also a standard unit. 

The unfinished part is the automatically generated attributes in `to_xarray`. This needs some kind of mapping and I'm not sure of the best place to start.

### CODE REVIEW

**Comment by gunnarvoet** [comment]
Thanks for starting this! I probably won't have time over the next couple weeks to look into this but think standardizing is a great idea in general!

**Comment by jessecusack** [comment]
I've standardized most (all?) variable names. I think the implementation works and can be merged. 

In the future I think the code that applies names and units to variables could be refactored out into a separate module.

**Comment by gunnarvoet** [comment]
Hi @jessecusack, I finally managed to look into this pull reqest. Following CF name conventions is great! Do you know if there is a CF convention for capitalizing (or not) in `long_name`? 

I am having trouble understanding why you convert time from `datetime64` to `seconds since 1970-01-01`. Currently, this means that the generated `Dataset` has time in `seconds since...`, not `datetime64`, which makes for ugly plots and other initial data wrangling before saving to netcdf. Doesn't saving to netcdf automatically convert to this time format?

> In the future I think the code that applies names and units to variables could be refactored out into a separate module.

This could indeed be great!

**Comment by jessecusack** [comment]
Hey @gunnarvoet, I refreshed myself on how xarray handles datetime64 and I think I mostly understand. In short, yes, we could just plop the `datetime64` array straight into the `Dataset` and let xarray handle the CF metadata. In this case, xarray will choose its own units, which may or may not be ok. The working example below illustrates this.

```python
import xarray as xr
import pandas as pd
import numpy as np

nanosecs_in_a_sec = 1e9
type_nanosec = "M8[ns]"  # numpy type string for datetime64[ns]

x_data = [1, 2, 3, 4, 5]
data_vars = dict(x=("time", x_data))
time = pd.date_range("2020-01-01", periods=len(x_data), freq="1H")

# In this dataset time is stored as a numpy.datetime64 (pandas date ranges have type datetime64)
attrs_dt = dict(standard_name="time", long_name="Time")
coords_dt = dict(time=("time", time.values, attrs_dt)) 
ds_dt = xr.Dataset(data_vars, coords_dt)
ds_dt.to_netcdf("ds_dt.nc")

# In this dataset time is stored as seconds since 1970-01-01
attrs_pos = dict(units="seconds since 1970-01-01", standard_name="time", long_name="Time")
time_pos = (time.values - np.datetime64("1970-01-01")).astype(type_nanosec).astype(float)/nanosecs_in_a_sec
coords_pos = dict(time=("time", time_pos, attrs_pos))
ds_pos = xr.Dataset(data_vars, coords_pos)
ds_pos.to_netcdf("ds_pos.nc")
```
Then I run `!ncdump -h ds_dt.nc && ncdump -h ds_pos.nc`, which gives:

```
netcdf ds_dt {
dimensions:
	time = 5 ;
variables:
	int64 x(time) ;
	int64 time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:units = "hours since 2020-01-01 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
}
netcdf ds_pos {
dimensions:
	time = 5 ;
variables:
	int64 x(time) ;
	double time(time) ;
		time:_FillValue = NaN ;
		time:units = "seconds since 1970-01-01" ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
}
```
So in this case, xarray chose the units `hours since 2020-01-01 00:00:00`. 

If we are happy letting xarray decide the units, then I think your method is fine. Especially if we anticipate that datasets will almost always be analysed using xarray, which decodes these time formats. If we want to ensure standardized time units across datasets then we should be explicit about the units. I don't have a strong opinion either way.

**Comment by jessecusack** [comment]
On your question about `long_name` capitalization, I find this:

> A long descriptive name for the variable (not necessarily from a controlled vocabulary). This attribute is recommended by the NetCDF Users Guide, the COARDS convention, and the CF convention.

from https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3. 

So it sounds like it is up to the creator to decide on capitalization. I personally like putting capitals on the first word, because that is how I like my axis labels formatted (e.g. Potential density, Conservative temperature etc. ). I am happy to change it to whatever you prefer for this package.

**Comment by gunnarvoet** [comment]
Hi @jessecusack, thanks for your great example on the time handling! This made me think though that we can't be the only ones who would like to save the time vector to a netcdf file with a specific encoding and sure enough xarray has a way to specify this. Adding to your example:
```python
# In this dataset we are explicit about time encoding in `to_netcdf()`
attrs_dt = dict(standard_name="time", long_name="Time")
coords_dt = dict(time=("time", time.values, attrs_dt))
ds_dt = xr.Dataset(data_vars, coords_dt)
ds_dt.to_netcdf("ds_enc.nc", encoding={
    "time": {"units": "seconds since 1970-01-01"},
    })
```
Running `ncdump -h ds_enc.nc` results in
```
netcdf ds_enc {
dimensions:
	time = 5 ;
variables:
	int64 x(time) ;
	int64 time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:units = "seconds since 1970-01-01" ;
		time:calendar = "proleptic_gregorian" ;
}
```
Reading the three examples back into xarray results in the exact same time vector for each of them.

I suggest we use this xarray method - what do you think?

**Comment by gunnarvoet** [comment]
As for the `long_name` capitalization I don't have a strong opinion. I usually do not capitalize but don't mind doing so. If we were to move this into a separate module it could have different sets of names for `long_name` and let the user decide but maybe that's overkill...

**Comment by jessecusack** [comment]
Good find on the encoding parameter! That is def. the right way to handle things. Wish I'd known about it sooner!

The ideal way to deal with CF attributes in a user-configurable way is to create a yaml file to store CF attributes associated with the variables. Then you can remove all the hard-coded CF and loop over all the xarray variables to put in the attributes. A user could edit the yaml to set the long_name they want. This is the kind of coding job for a long cruise transit... 

I changed the time handling and added your encoding suggestion. I think the pull request is good to go, if you're happy.

**Comment by gunnarvoet** [comment]
Thanks @jessecusack for all your work on this!!

**Pull request merged**
